### ISSUE TITLE
Updating the Column Map

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#126]
With the addition of Ensemble.assign, users can now add columns derived from other columns. It's reasonable to expect a user to assign a new column, then want to replace an existing critical column with their new column. For example, a modified flux or shifted time column.

We should add an Ensemble.update_column_map function, which takes in a new ColumnMapper object or just the direct kwargs

**Comment by jeremykubica** [comment]
Do we want this to be a full update (i.e. call `_load_column_mapper`) or should this also support partial updates of a few columns?

**Comment by dougbrn** [comment]
I'm thinking partial assignment would be important for this to capture, this function could just build an initial ColumnMapper object from the Ensemble critical columns and then update that with the inputs from this function.

**Comment by jeremykubica** [comment]
Sounds good.
