### ISSUE TITLE
Add some functionality to preview the columns of a parquet file before load

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#128]
The Ensemble needs columns mapped on load from a given data source, requiring the user to know what columns are available before calling ensemble.from_parquet (or equivalent). We should introduce some kind of ensemble function ("Ensemble.peek"?) that returns some column label information for users to read to inform their mapping assignments. This could even just be a utils function. Assuming this is a utils function, workflow would look like:
```
ens = Ensemble()

tape.utils.peek(path_to_data)  # returns a list of columns for the source and object tables

# user identifies which columns they think are interesting

colmap=ColumnMapper(user_defined_mappings)

[Load into Ensemble using loader method of choice]
```

**Comment by jeremykubica** [comment]
I would advocate for this to be a util function.

**Comment by dougbrn** [comment]
Nice find, that seems sufficient to wrap into a utils function. Although, should we even make utils functions that just wrap useful things from other packages? It might be sufficient to just say in documentation: "use pyarrow.parquet.read_schema to preview the schema of a given file", with a brief example

**Comment by jeremykubica** [comment]
I was thinking that it is probably sufficient to mention it in the documentation instead of wrapping it. But I am fine either way.

**Comment by dougbrn** [comment]
I agree with you, will close this for now.
