### ISSUE TITLE
Allow ensemble to use an existing dask cluster

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#21]
Currently, Dask will always spin up a new cluster for an ensemble object. To improve practical usage, we'd want to also facilitate instances where the user has an existing cluster that they'd like to use instead. Hopefully, this is a simple modification. Should be a good first step towards compatibility with cloud computing services.

**Comment by dougbrn** [comment]
Per the [documentation](https://distributed.dask.org/en/stable/client.html), the ability to do this may already be implemented. By passing **kwargs into the client call, the user should be able to point at an existing scheduler, further evidenced by the AWS documentation: https://aws.amazon.com/blogs/machine-learning/machine-learning-on-distributed-dask-using-amazon-sagemaker-and-aws-fargate/ 

Unclear still whether this is the best way to handle this though. For example, in the aws docs they call client.restart() to allocate new resources. We technically will have access at the same level using self.client.restart(), but does this motivate handling the client more explicitly? Thinking the best way forward for now is to proceed with the current minimal client implementation and see what pain points emerge when trying this on the cloud. Detailed documentation may be sufficient.

**Comment by nevencaplar** [comment]
Some questions that have come out offline discussions last few weeks:

- Can you run on a single machine and multiple machines (I believe the answer is yes)

- If you are running on a cloud, how to make that as cheap as possible

- If you have to spin up dask cluster, does every user has to do that  - if yes, how to do that best? (I believe that the answer is no - not every user has to spin up dask cluster)  

- Can you  share resources (e.g., the input data); can you spin up on-spot instances and each user shares the fractions of resources
