### ISSUE TITLE
Implement improvements to structure-function

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#22]
-  Add error estimate for structure function estimation via bootstrapping. Resample all of the points in a time bin and recompute the structure-function - do it e.g, 100 times and note 1-sigma limits.

- Allow for the creation of automatic time bins in which structure function is calculated (similar as it is possible to do with Lomb-Scargle periodogram calculation). Add following options:
    - Time bins so that each time bin has the same number of points
    - Time bins so that each time bin has the same length of time
    - Time bins so that each time bin has same log length of time 

- Make sure that nan-s and other artifacts do not break the evaluation of the structure-function

- Implement non-dictionary output from the calculation; the output should be in a format that is easily accessible with standard python data manipulation methods.

**Comment by dougbrn** [comment]
Marking this as resolved due to #25 , the request for bootstrapping will be added to the other issue
