### ISSUE TITLE
Further enhancement of structure function and capability to calculate the result for ensemble

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#23]
- Calculate structure function for an ensemble of lightcurves
	- sample the points so that each object has the same weight
	- sample all points equally - this has the problem that lightcurves that have more datapoints dominate the ensemble

- Different implementations of the structure function (by this, I mean different equations - reference for these different equations is here: TBD )

-  Combine points that have been taken during the same night - take mean, and increase errors

-  Simple filtering on the light curves
	- sigma clipping
	-``AGN specific’’ clipping - problem with sigma clipping is that it is not good for lightcurves that change brightness - I need to further specify this

**Comment by dougbrn** [comment]
Additionally, from #22:

Add error estimate for structure function estimation via bootstrapping. Resample all of the points in a time bin and recompute the structure-function - do it e.g, 100 times and note 1-sigma limits.

**Comment by nevencaplar** [comment]
This issue has been elaborated in better pointed https://github.com/lincc-frameworks/lsstseries/issues/59, https://github.com/lincc-frameworks/lsstseries/issues/60, https://github.com/lincc-frameworks/lsstseries/issues/61, https://github.com/lincc-frameworks/lsstseries/issues/62
