### ISSUE TITLE
Add Dask client closing to ensemble class

### ISSUE THREAD

**Issue by smcguire-cmu** [lincc-frameworks/lsstseries#31]
The Dask client class has a `close` method that performs teardown on the client. It would be useful to add a way to call this through the client class, which could solve problems that can occur during repeated running of the class, e.g. in running unit tests. (This is currently solved in a bit of a hacky way by closing the client directly in the unit tests)

One solution could be to add `__enter__` and `__exit__` methods to the class, so that it can be used with the python `with` statement, as shown [here](https://www.geeksforgeeks.org/with-statement-in-python/).

**Comment by dougbrn** [comment]
Implemented in #36
