### ISSUE TITLE
Filtering and Column Arithmetic

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#44]
Filtering the ensemble on a given column is a core requirement for the ensemble actually being useful. As a somewhat related extension, the ability to add new columns given arithmetic on existing columns (or any criteria) is desirable. These two things will enable useful functionality such as color cuts, which would be implemented as a function that creates a color column and then filters on some color threshold.

**Comment by dougbrn** [comment]
My thinking is that whatever we choose to do should be consistent across the functions that modify the object/source tables. Currently, that is more to the alternative, where ens.filter would update ens._source or ens._object directly, though we also return the ensemble object back as well. The advantage of it being that a user avoids the subtle issue of doing something like:
```
ens.filter()

ens.info() # Why didn't my filter work??
```

Returning a view may also be in light conflict with dask and it's lazy loading, as we would just return the lazy dataframe object view and the user would still need to call a compute() to actual execute the task graph.

**Comment by jeremykubica** [comment]
How should the criteria specification work on this. I can imagine a few scenarios:
1) Predefined criteria (equals, less than, etc.)
2) Passing a function to be evaluated on each row
3) Passing an arbitrary string with the condition, allowing things like `df[df["col_name1"] < 3 or df["col_name2"] == "Hello"]`

What would be most useful here?
