### ISSUE TITLE
calc_sf2 pandas.qcut bottleneck

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#46]
Dask profiling on batch runs of calc_sf2 suggests that pandas.qcut is taking over half of the compute time. Should investigate this and potential replacements.

![Screen Shot 2023-03-09 at 12 56 19 PM](https://user-images.githubusercontent.com/8853505/224156404-d443eb9d-5089-440a-9a2a-c044611b629f.png)

**Comment by jeremykubica** [comment]
Do you need to remove duplicates? If not, I think the following code work in qcuts place:

`num_quantiles = int(np.ceil(len(dts) / sthresh))`
`quantiles = np.linspace(0.0, 1.0, num_quantiles + 1)`
`bins = np.quantile(dts, quantiles)`
`return bins`

I timed it out and the numpy version is about 8x faster.

**Comment by jeremykubica** [comment]
At least partially helped by #52
