### ISSUE TITLE
Add an easy way to get band-specific data

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/lsstseries#55]
Potentially just a wrapper around a[ yet-to-be-implemented filter call](#44 ) and [yet-to-be-implemented select call](#54 ), but the current way is painful, see below:

`ensemble._data[ensemble._data['band'] == 'desired_band']`

**Comment by jeremykubica** [comment]
This can be done with the new `query` function as `ens.query("band == 'g'", table="source")` as of PR #118. There is an example of this in the `ensemble.py` comments.
