### ISSUE TITLE
Various definitions of structure function

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#60]
We want to support several definitions of structure function as they all have different strengths and weaknesses. 

- Implement Equation 10 from [Kozlowski 16](https://arxiv.org/abs/1604.05858) (interquartile definition) as a possibility (see also [Graham+ 16](https://arxiv.org/abs/1401.1785), it is equation referenced here as Macleod+ 2012)
  
- Implement Bauer 2009 and S10 equations from [Graham+ 16](https://arxiv.org/abs/1401.1785)

**Comment by drewoldag** [comment]
For `macleod_2012` N = the number of delta_magnitude values in a given delta_time bin.

**Comment by drewoldag** [comment]
S10 equation citation: 
Schmidt et al. 2010, 2010ApJ...714.1194S [https://arxiv.org/abs/1002.2642] https://iopscience.iop.org/article/10.1088/0004-637X/714/2/1194/pdf
Schmidt et al. 2010 Erratum, 2010ApJ...721.1941S https://iopscience.iop.org/article/10.1088/0004-637X/721/2/1941/pdf
