### ISSUE TITLE
Estimate error on the measurement of structure function in each delta_t bin

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#62]
The goal is to enable an estimate of the uncertainty on the calculated structure function.

Resample pairs of measurements randomly with repetition M times (I recommend 100 times; possibly add exact value of M as an option).
If you are in ``object have the same weight mode’’, select new N measurements from lightcurve that have more measurements each time.
Calculate the median of these 100 measurements and 16 to 83 quantile - report that as 1-sigma errors of the measurement (allow for the possibility to report different upper and lower errors).

**Comment by drewoldag** [comment]
Report 1_sigma as (83-16)/2 
Provide option for user to output lower_error as median-16 and upper_error as 83-median.
