### ISSUE TITLE
Tutorial for structure function

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#68]
Create a tutorial notebook which covers functionality implemented in [59](https://github.com/lincc-frameworks/lsstseries/issues/59), [60](https://github.com/lincc-frameworks/lsstseries/issues/60), [61](https://github.com/lincc-frameworks/lsstseries/issues/61), [62](https://github.com/lincc-frameworks/lsstseries/issues/62)

**Comment by drewoldag** [comment]
Be sure to include information about how to work with StructureFunctionLightCurve objects, both the primary and derived data.
