### ISSUE TITLE
Bin data taken during given time-frame, default==same night

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#71]
Implement binning function that combines data taken during the same night, in the same band; assuming there was no intrinsic change of luminosity during this time window and that these observations can be combined in order to decrease the uncertainty. Add an option to have custom duration of time over which data is averaged, larger or smaller than default value of ``1 night''.

**Comment by nevencaplar** [comment]
1. I would not include any detection mechanism in this function. It is to the discretion of user to decide if it makes sense this. In general, e.g., in AGN the change of flux on one-night time scales is much smaller than the sensitivity so it makes sense to combine. But if you were hunting for supernovae it would not make sense.

2. Yes, I agree. Assume that errors are perfectly Gaussian and with sigmas stored in error column.

**Comment by jeremykubica** [comment]
Closed with #90
